export const trafficData = [{
    name: '不限',
    value: 0
}, {
    name: '北京南苑机场',
    value: 1
}, {
    name: '首都机场T3航站楼',
    value: 2
}, {
    name: '首都机场T2航站楼',
    value: 3
}, {
    name: '首都机场T1航站楼',
    value: 4
}, {
    name: '北京站',
    value: 5
}, {
    name: '北京西站',
    value: 6
}, {
    name: '北京北站',
    value: 7
}, {
    name: '北京南站',
    value: 8
}, {
    name: '东直门长途汽车站',
    value: 9
}, {
    name: '天桥长途汽车站',
    value: 10
}, {
    name: '德胜门长途汽车站',
    value: 11
}, {
    name: '丽泽桥长途汽车站',
    value: 12
}, {
    name: '西直门汽车客运站',
    value: 13
}, {
    name: '莲花池长途汽车站',
    value: 14
}, {
    name: '北京北郊长途汽车站',
    value: 15
}, {
    name: '四惠长途汽车站',
    value: 16
}, {
    name: '永定门长途汽车站',
    value: 17
}, {
    name: '八王坟长途汽车站',
    value: 18
}, {
    name: '北京南站长途汽车站',
    value: 19
}, {
    name: '木樨园长途汽车站',
    value: 20
}, {
    name: '六里桥长途客运站',
    value: 21
}, {
    name: '新发地长途客运站',
    value: 22
}, {
    name: '赵公口长途客运站',
    value: 23
}];
export const localData = [{
    name: '不限',
    value: 0
}, {
    name: '首都机场',
    value: '1'
}, {
    name: '东直门商圈',
    value: '2'
}, {
    name: '王府井商圈',
    value: '3'
}, {
    name: '前门商圈',
    value: '4'
}, {
    name: '三里屯，工体',
    value: '5'
}, {
    name: '后海，什刹海',
    value: '6'
}];
export const distanceData = [{
    name: '全城',
    value: 0
}, {
    name: '500m',
    value: 500
}, {
    name: '1km',
    value: 1
}, {
    name: '2km',
    value: 2
}, {
    name: '3km',
    value: 3
}, {
    name: '5km',
    value: 5
}];
export const reginData = [{
    name: '不限',
    value: 0
}, {
    name: '东城区',
    value: 1
}, {
    name: '西城区',
    value: 2
}, {
    name: '朝阳区',
    value: 3
}, {
    name: '丰台区',
    value: 4
}, {
    name: '石景山区',
    value: 5
}, {
    name: '海淀区',
    value: 6
}, {
    name: '门头沟区',
    value: 7
}, {
    name: '房山区',
    value: 8
}, {
    name: '通州区',
    value: 9
}, {
    name: '顺义区',
    value: 10
}, {
    name: '昌平区',
    value: 11
}, {
    name: '大兴区',
    value: 12
}, {
    name: '怀柔区',
    value: 13
}, {
    name: '平谷区',
    value: 14
}, {
    name: '密云县',
    value: 15
}, {
    name: '延庆县',
    value: 16
}];
export const toturistAttractionData = {
    urban: [{
        name: '不限',
        value: 0
    }, {
        name: '天安门',
        value: 1
    }, {
        name: '南锣鼓巷',
        value: 2
    }, {
        name: '鸟巢',
        value: 3
    }, {
        name: '故宫',
        value: 4
    }, {
        name: '天坛',
        value: 5
    }, {
        name: '北京动物园',
        value: 6
    }, {
        name: '颐和园',
        value: 7
    }, {
        name: '欢乐谷',
        value: 8
    }, {
        name: '雍和宫',
        value: 9
    }, {
        name: '鼓楼',
        value: 10
    }, {
        name: '什刹海',
        value: 11
    }, {
        name: '798艺术区',
        value: 12
    }, {
        name: '水立方',
        value: 13
    }, {
        name: '北海公园',
        value: 14
    }, {
        name: '朝阳公园',
        value: 15
    }, {
        name: '圆明园',
        value: 16
    }, {
        name: '奥林匹克公园',
        value: 17
    }, {
        name: '中国科技馆',
        value: 18
    }, {
        name: '国家大剧院',
        value: 19
    }, {
        name: '军事博物馆',
        value: 20
    }, {
        name: '世界公园',
        value: 21
    }, {
        name: '大观园',
        value: 22
    }, {
        name: '恭王府',
        value: 23
    }, {
        name: '国家博物馆',
        value: 24
    }],
    suburbs: [{
        name: '就是不限',
        value: 0
    }, {
        name: '天安门',
        value: 1
    }, {
        name: '南锣鼓巷',
        value: 2
    }, {
        name: '鸟巢',
        value: 3
    }, {
        name: '故宫',
        value: 4
    }, {
        name: '天坛',
        value: 5
    }, {
        name: '北京动物园',
        value: 6
    }, {
        name: '颐和园',
        value: 7
    }, {
        name: '欢乐谷',
        value: 8
    }, {
        name: '雍和宫',
        value: 9
    }, {
        name: '鼓楼',
        value: 10
    }, {
        name: '什刹海',
        value: 11
    }, {
        name: '798艺术区',
        value: 12
    }, {
        name: '水立方',
        value: 13
    }, {
        name: '北海公园',
        value: 14
    }, {
        name: '朝阳公园',
        value: 15
    }, {
        name: '圆明园',
        value: 16
    }, {
        name: '奥林匹克公园',
        value: 17
    }, {
        name: '中国科技馆',
        value: 18
    }, {
        name: '国家大剧院',
        value: 19
    }, {
        name: '军事博物馆',
        value: 20
    }, {
        name: '世界公园',
        value: 21
    }, {
        name: '大观园',
        value: 22
    }, {
        name: '恭王府',
        value: 23
    }, {
        name: '国家博物馆',
        value: 24
    }]
};
export const subWayData = {
    1: [{
        name: '不限',
        value: 0
    }, {
        name: '四惠东地铁站',
        value: 1
    }, {
        name: '四惠地铁站',
        value: 2
    }, {
        name: '大望路地铁站',
        value: 3
    }, {
        name: '国贸地铁站',
        value: 4
    }, {
        name: '永安里地铁站',
        value: 5
    }, {
        name: '建国门地铁站',
        value: 6
    }, {
        name: '东单地铁站',
        value: 7
    }, {
        name: '王府井地铁站',
        value: 8
    }, {
        name: '天安门东地铁站',
        value: 9
    }, {
        name: '天安门西地铁站',
        value: 10
    }, {
        name: '西单地铁站',
        value: 11
    }, {
        name: '复兴门地铁站',
        value: 12
    }, {
        name: '南礼士路地铁站',
        value: 13
    }, {
        name: '木樨地地铁站',
        value: 14
    }, {
        name: '军事博物馆地铁站',
        value: 15
    }, {
        name: '公主坟地铁站',
        value: 16
    }, {
        name: '万寿路地铁站',
        value: 17
    }, {
        name: '五棵松地铁站',
        value: 18
    }, {
        name: '玉泉路地铁站',
        value: 19
    }, {
        name: '八宝山地铁站',
        value: 20
    }, {
        name: '八角游乐园地铁站',
        value: 21
    }, {
        name: '古城地铁站',
        value: 22
    }, {
        name: '苹果园地铁站',
        value: 23
    }],
    2: [{
        name: '东直门地铁站',
        value: 1
    }, {
        name: '东四十条地铁站',
        value: 2
    }, {
        name: '朝阳门地铁站',
        value: 3
    }, {
        name: '建国门地铁站',
        value: 4
    }, {
        name: '北京站地铁站',
        value: 5
    }, {
        name: '崇文门地铁站',
        value: 6
    }, {
        name: '前门地铁站',
        value: 7
    }, {
        name: '和平门地铁站',
        value: 8
    }, {
        name: '宣武门地铁站',
        value: 9
    }, {
        name: '长椿街地铁站',
        value: 10
    }, {
        name: '复兴门地铁站',
        value: 11
    }, {
        name: '阜成门地铁站',
        value: 12
    }, {
        name: '车公庄地铁站',
        value: 13
    }, {
        name: '西直门地铁站',
        value: 14
    }, {
        name: '积水潭地铁站',
        value: 15
    }, {
        name: '鼓楼大街地铁站',
        value: 16
    }, {
        name: '安定门地铁站',
        value: 17
    }, {
        name: '雍和宫地铁站',
        value: 18
    }]
};
