module.exports = {
    "ret": true,
    "data": {
        "hotCities": [
            ["bangkok", "曼谷", "B"],
            ["koh_phuket_tha", "普吉", "K"],
            ["singapore_city", "新加坡", "S"],
            ["seoul", "首尔", "S"],
            ["taipei", "台北市", "T"],
            ["chiang_mai", "清迈府", "C"],
            ["tokyo", "东京", "T"],
            ["osaka", "大阪", "O"],
            ["bali", "巴厘岛", "B"],
            ["jeju", "济州岛", "J"],
            ["kenting", "垦丁", "K"],
            ["ko_samui_district", "苏梅岛", "K"],
            ["sabah", "沙巴", "S"],
            ["pattaya", "芭提雅", "P"],
            ["kuala_lumpur", "吉隆坡", "K"],
            ["kyoto_kyo", "京都", "K"],
            ["maldives", "马尔代夫", "M"],
            ["kaohsiung", "高雄市", "K"]
        ],
        "allCities": [
            ["a_coruna", "拉科鲁尼亚", "A"],
            ["aberdeenshire_sco", "阿伯丁郡", "A"],
            ["abu_dhabi_abu", "阿布扎比", "A"],
            ["abuta_district", "虻田郡", "A"],
            ["accra_acc", "阿克拉", "A"],
            ["achaea_dyt", "阿哈伊亚州", "A"],
            ["addis_ababa_add", "亚的斯亚贝巴", "A"],
            ["adelaide_sa", "阿德莱德", "A"],
            ["aden", "亚丁", "A"],
            ["agra_up", "阿格拉", "A"],
            ["ain_sebaa_hay_mohammedi", "Ain Sebaa Hay Mohammedi", "A"],
            ["airlie_beach", "艾尔利滩", "A"],
            ["aix_en_provence", "普罗旺斯地区艾克斯", "A"],
            ["ajman_ajm", "阿治曼", "A"],
            ["alameda_county", "阿拉米达县", "A"],
            ["alava_pv", "阿拉瓦", "A"],
            ["albacete_cm", "阿尔巴塞特", "A"],
            ["alexandria_ale", "亚历山大", "A"],
            ["algiers_alg", "阿尔及尔", "A"],
            ["alicante_val", "阿利坎特,瓦伦西亚", "A"],
            ["allegheny", "阿利根尼县", "A"],
            ["almaty_tal", "阿拉木图", "A"],
            ["almeria", "阿尔梅里亚", "A"],
            ["alphen_chaam", "Alphen Chaam", "A"],
            ["amersfoort_ut", "阿默斯福特", "A"],
            ["amman_amm", "安曼", "A"],
            ["anchorage_ak", "安克雷奇", "A"],
            ["angeles_city", "安吉利斯", "A"],
            ["annecy_hau", "安纳西", "A"],
            ["ansan_si", "安山", "A"],
            ["antalya_tr", "安塔利亚", "A"],
            ["antwerp_an", "安特卫普", "A"],
            ["anuradhapura", "阿努拉德普勒", "A"],
            ["argolis", "阿尔戈利斯州", "A"],
            ["argyll_and_bute_sco", "阿盖尔 比特", "A"],
            ["arraijan", "阿赖汉", "A"],
            ["asahikawa_hok", "旭川", "A"],
            ["ashigarashimo_district", "足柄下郡", "A"],
            ["assisi", "阿西西", "A"],
            ["astana_tse", "阿斯坦纳", "A"],
            ["asturias_pri", "阿斯图里亚斯", "A"],
            ["aswan_asw", "阿斯旺", "A"],
            ["atami_shi", "热海市", "A"],
            ["atlantic", "大西洋县", "A"],
            ["auckland_auc", "奥克兰,奥克兰", "A"],
            ["aveiro_district", "阿维罗", "A"],
            ["avignon_vau", "阿维尼翁", "A"],
            ["avila", "阿维拉省", "A"],
            ["azores", "亚速尔群岛", "A"],
            ["ba_ria_vung_tau", "巴地 斗顿", "B"],
            ["badajoz", "巴达霍斯", "B"],
            ["badulla", "巴杜勒", "B"],
            ["bagan", "蒲甘", "B"],
            ["baku_az", "巴库", "B"],
            ["balearic_islands", "巴利阿里群岛", "B"],
            ["bali", "巴厘岛", "B"],
            ["baltimore_md_us", "巴尔的摩市", "B"],
            ["bandung_wes", "万隆", "B"],
            ["banff_div", "班夫", "B"],
            ["bangalore_rural", "Bangalore Rural", "B"],
            ["bangalore_urban", "Bangalore Urban", "B"],
            ["bangkok", "曼谷", "B"],
            ["barcelona", "巴塞罗那省", "B"],
            ["bari_ba", "巴里", "B"],
            ["barnstable", "巴恩斯特布尔县", "B"],
            ["batam_ria", "巴淡岛", "B"],
            ["bath_and_north_east_somer", "巴思 东北萨默塞特", "B"],
            ["batu_feringgi_pen", "巴都菲宁宜", "B"],
            ["bayan_lepas_pen", "巴彦勒帕斯", "B"],
            ["beirut_bei", "贝鲁特,贝鲁特省", "B"],
            ["beja_district", "贝雅", "B"],
            ["belfast_nor", "贝尔法斯特", "B"],
            ["beppu", "别府市", "B"],
            ["bergen_hor", "卑尔根", "B"],
            ["bergen_nj", "博根县", "B"],
            ["berks", "伯克县,宾西法尼亚", "B"],
            ["berlin_ber", "柏林", "B"],
            ["berne_ber", "伯尔尼", "B"],
            ["bexar", "比尔县", "B"],
            ["binh_thuan_province", "平顺省", "B"],
            ["bintan_ria", "民丹岛", "B"],
            ["biscay", "比斯卡亚", "B"],
            ["bishkek_chu", "比什凯克", "B"],
            ["bodrum_mug", "博都茹姆", "B"],
            ["bohol_visayas", "保和", "B"],
            ["bojanala", "Bojanala", "B"],
            ["bologna_bo", "博洛尼亚", "B"],
            ["boracay_philippines", "长滩岛", "B"],
            ["bordeaux", "波尔多", "B"],
            ["bornholm_cap", "博恩霍姆岛", "B"],
            ["bosveld", "Bosveld", "B"],
            ["boulder", "博尔德,科罗拉多州", "B"],
            ["braga", "布拉加", "B"],
            ["braganca_district", "布拉干萨区", "B"],
            ["brasilia_df", "巴西利亚", "B"],
            ["bratislava", "布拉迪斯拉发", "B"],
            ["breede_river_dc", "Breede River DC", "B"],
            ["bremen", "不来梅", "B"],
            ["brevard", "布里瓦德县", "B"],
            ["brisbane_qld", "布里斯班", "B"],
            ["brno_brn", "布尔诺", "B"],
            ["broward", "布劳沃德县", "B"],
            ["bruges_wv", "布鲁日,西佛兰德", "B"],
            ["brussels", "布鲁塞尔", "B"],
            ["bucharest", "布加勒斯特", "B"],
            ["buckinghamshire_eng", "白金汉郡", "B"],
            ["budapest", "布达佩斯", "B"],
            ["buenos_aires", "布宜诺斯艾利斯", "B"],
            ["buffalo_ne", "布法罗", "B"],
            ["buncombe", "班康县", "B"],
            ["burgos", "布尔戈斯", "B"],
            ["busan_kr", "釜山", "B"],
            ["butterworth_pen", "北海,平安岛", "B"],
            ["caceres", "卡塞雷斯", "C"],
            ["cadiz", "加的斯市", "C"],
            ["cairns_qld", "凯恩斯", "C"],
            ["cairo_cai", "开罗", "C"],
            ["calgary_div", "卡尔加里", "C"],
            ["cambridgeshire_eng", "剑桥郡", "C"],
            ["canberra_act", "堪培拉", "C"],
            ["cancun_qroo", "坎昆", "C"],
            ["cankaya", "Cankaya", "C"],
            ["cannes_alp", "戛纳", "C"],
            ["cantabria_can", "坎塔布里亚", "C"],
            ["cape_town", "开普敦", "C"],
            ["caracas_lib", "加拉加斯", "C"],
            ["cardiff_wal", "加的夫", "C"],
            ["carlsbad", "卡罗维发利", "C"],
            ["castellon_val", "卡斯特利翁", "C"],
            ["castelo_branco_district", "布朗库堡", "C"],
            ["cebu_city", "宿务", "C"],
            ["centre_pa", "申特县", "C"],
            ["cesky_krumlov", "捷克克鲁姆洛夫", "C"],
            ["cesme", "切什米", "C"],
            ["chacabuco_cha", "查卡布科", "C"],
            ["chalkidiki_ken", "哈尔基季基半岛", "C"],
            ["chamant_ois", "夏门", "C"],
            ["champaign", "尚佩恩县", "C"],
            ["chang_hua", "彰化县", "C"],
            ["chania", "干尼亚州", "C"],
            ["chennai", "钦奈,泰米尔纳德", "C"],
            ["cheshire_west_and_chester", "Cheshire West and Chester", "C"],
            ["chester_lun", "切斯特", "C"],
            ["chiang_mai", "清迈府", "C"],
            ["chiang_rai_th", "清莱", "C"],
            ["chiayi", "嘉义", "C"],
            ["chiba_chi", "千叶", "C"],
            ["chita_g", "赤塔", "C"],
            ["chitose", "千岁市", "C"],
            ["chon_buri_th", "春武里府", "C"],
            ["christchurch_chr", "基督城", "C"],
            ["city_of_bristol", "布里斯托尔市", "C"],
            ["city_of_edinburgh", "爱丁堡", "C"],
            ["ciudad_real", "雷阿尔城,卡斯蒂利亚 拉曼查", "C"],
            ["clare_cla", "克莱尔郡", "C"],
            ["clark_county_nv", "克拉克县,内达华州", "C"],
            ["coconino", "可可尼诺县", "C"],
            ["coimbra_district", "科英布拉", "C"],
            ["cologne_k", "科隆", "C"],
            ["colombo_wp", "科伦坡", "C"],
            ["constanta", "康斯坦察", "C"],
            ["cook_il", "库克县", "C"],
            ["coos", "库斯县,新罕布什尔州", "C"],
            ["cordoba_al", "科多巴", "C"],
            ["corfu", "科孚,伊奥尼亚群岛", "C"],
            ["corinthia", "科林西亚州", "C"],
            ["cork_cor", "科克", "C"],
            ["cornwall", "康沃尔", "C"],
            ["coron", "科伦", "C"],
            ["county_durham_eng", "达拉谟", "C"],
            ["cuenca", "昆卡", "C"],
            ["cumbria", "坎布里亚郡", "C"],
            ["cusco_cuz", "库斯科", "C"],
            ["cuyahoga", "凯霍加县", "C"],
            ["da_nang_vn", "岘港", "D"],
            ["daegu_kr_sou", "大邱", "D"],
            ["daejeon_kr_sou", "大田", "D"],
            ["dallas_tx", "达拉斯", "D"],
            ["dane", "戴恩县", "D"],
            ["dauphin_pa", "Dauphin", "D"],
            ["davao_city_dav", "达沃", "D"],
            ["denver_co", "丹佛", "D"],
            ["derbyshire_eng", "德贝郡", "D"],
            ["derry", "德里", "D"],
            ["devon_eng", "德文郡", "D"],
            ["dhaka_dha", "达卡", "D"],
            ["dickinson", "迪金森县", "D"],
            ["district_of_columbia", "哥伦比亚特区", "D"],
            ["doha_doh", "多哈", "D"],
            ["donegal", "多内加尔", "D"],
            ["dorset", "多塞特", "D"],
            ["dortmund_arn", "多特蒙德", "D"],
            ["dresden_dd", "德累斯顿", "D"],
            ["dubai", "迪拜", "D"],
            ["dublin_city_dub", "Dublin City", "D"],
            ["dubrovnik_opc", "杜布罗夫尼克", "D"],
            ["dumaguete_city", "杜马格特", "D"],
            ["dumfries_and_galloway_sco", "丹弗里斯 加洛韦", "D"],
            ["dupage", "杜佩奇县", "D"],
            ["dusseldorf_d", "杜塞尔多夫", "D"],
            ["dutchess", "达奇斯县", "D"],
            ["east_attica", "东阿提卡州", "E"],
            ["east_rand", "East Rand", "E"],
            ["east_susx", "东萨塞克斯", "E"],
            ["edmonton_div", "埃德蒙顿", "E"],
            ["ehlanzeni", "Ehlanzeni", "E"],
            ["el_nido", "爱妮岛", "E"],
            ["erie", "伊利县", "E"],
            ["essex", "艾塞克斯", "E"],
            ["essex_ma_us", "Essex,马萨诸塞州", "E"],
            ["essex_nj", "艾塞克斯郡", "E"],
            ["euboea", "优卑亚岛", "E"],
            ["evora_district", "埃武拉区", "E"],
            ["famagusta", "法马古斯塔区", "F"],
            ["faro_district", "法鲁", "F"],
            ["fasano", "法萨诺", "F"],
            ["fayette_tn", "费耶特县,田纳西", "F"],
            ["fethiye", "费特希耶", "F"],
            ["fife", "法伊夫", "F"],
            ["fiji_fij", "斐济", "F"],
            ["florence", "佛罗伦萨", "F"],
            ["florida_flo", "佛罗里达", "F"],
            ["frankfurt_da", "法兰克福", "F"],
            ["franklin_oh_us", "富兰克林,Ohio", "F"],
            ["fuji_shi", "富士市", "F"],
            ["fujiyoshida", "富士吉田市", "F"],
            ["fukuoka_fuk", "福冈市", "F"],
            ["fulton_ga", "富尔顿县", "F"],
            ["furano", "富良野市", "F"],
            ["fussen", "菲森", "F"],
            ["gallatin_mt", "加拉廷县", "G"],
            ["galle", "加勒", "G"],
            ["galway_gal", "戈尔韦,戈尔韦", "G"],
            ["gampaha_wp", "加姆珀哈", "G"],
            ["gdansk_gda", "格但斯克", "G"],
            ["geneva_gen", "日内瓦", "G"],
            ["genting_highlands_pah", "云顶高原", "G"],
            ["george_town_pen", "乔治市", "G"],
            ["gifu_gif", "岐阜", "G"],
            ["gipuzkoa", "吉普斯考", "G"],
            ["girona", "赫罗纳", "G"],
            ["glasgow_city", "格拉斯哥市", "G"],
            ["gloucestershire", "格洛斯特郡", "G"],
            ["gold_coast_qld", "黄金海岸", "G"],
            ["gotenba", "御殿场市", "G"],
            ["gothenburg_se", "哥德堡", "G"],
            ["government_of_amsterdam", "阿姆斯特丹", "G"],
            ["government_of_rotterdam", "鹿特丹", "G"],
            ["goyang_si_gye", "高阳市", "G"],
            ["grafton_nh", "格拉夫顿县", "G"],
            ["granada_al", "格拉纳达", "G"],
            ["great_barrier_reef", "大堡礁", "G"],
            ["greene_ny_us", "Greene,New York", "G"],
            ["grindelwald_int", "格林德瓦", "G"],
            ["gt_lon", "大伦敦", "G"],
            ["gt_man", "大曼彻斯特", "G"],
            ["guadalajara_cm", "瓜达拉哈拉", "G"],
            ["guadalajara_jal", "瓜达拉哈拉,哈利斯科州", "G"],
            ["guam", "关岛", "G"],
            ["guarda_district", "瓜达,葡萄牙", "G"],
            ["guldborgsund_municipality", "古尔堡松自治市", "G"],
            ["gurgaon", "古尔冈", "G"],
            ["gwangju_kr_sou", "光州", "G"],
            ["gwangju_si", "广州市,京畿道", "G"],
            ["gwynedd_wal", "圭内斯", "G"],
            ["gyeongju_si", "庆州", "G"],
            ["haarlemmermeer", "哈勒默梅尔", "H"],
            ["hai_duong_vn", "海阳市", "H"],
            ["hai_phong_vn", "海防市", "H"],
            ["hakodate", "函馆市", "H"],
            ["hakusan_ish", "白山市", "H"],
            ["halifax_hal", "哈利法克斯", "H"],
            ["hallstatt", "哈尔施塔特", "H"],
            ["hambantota", "汉班托塔", "H"],
            ["hamburg_ham", "汉堡", "H"],
            ["hamilton_island", "汉密尔顿岛", "H"],
            ["hamilton_oh_us", "Hamilton,Ohio", "H"],
            ["hampshire_eng", "汉普郡", "H"],
            ["hancock_me_us", "汉考克县,Maine", "H"],
            ["hanoi_vn", "河内", "H"],
            ["hanover_han", "汉诺威", "H"],
            ["harbour_island", "哈勃岛", "H"],
            ["harris_tx", "哈里斯县,德克萨斯州", "H"],
            ["hartford_ct_us", "哈特福德", "H"],
            ["hatta_dub", "哈特姆", "H"],
            ["havana", "哈瓦那", "H"],
            ["hawaii_county", "夏威夷", "H"],
            ["heidelberg_rhe", "海德堡", "H"],
            ["helmstedt", "赫姆斯塔德", "H"],
            ["helsinki_hel", "赫尔辛基", "H"],
            ["hennepin", "亨内平县", "H"],
            ["heraklion_cre", "伊拉克利翁州", "H"],
            ["hertfordshire_eng", "赫特福德郡", "H"],
            ["highld", "Highland", "H"],
            ["hillsborough", "希尔斯波罗县", "H"],
            ["hiroshima_hir", "广岛市", "H"],
            ["ho_chi_minh_city", "胡志明市", "H"],
            ["hobart_tas_au", "霍巴特", "H"],
            ["hokkaido", "北海道", "H"],
            ["honolulu_county", "檀香山市县", "H"],
            ["horry", "霍里县", "H"],
            ["houston_ga", "休斯敦", "H"],
            ["houston_tx", "休斯顿,德克萨斯州", "H"],
            ["houx_na", "乌镇,纳慕尔", "H"],
            ["hualian", "花莲县", "H"],
            ["hudson", "哈德逊县", "H"],
            ["hue_vn_vie", "顺化", "H"],
            ["huelva", "韦尔瓦", "H"],
            ["huesca", "韦斯卡", "H"],
            ["hung_yen_province", "兴安", "H"],
            ["hurghada_qes", "古尔代盖", "H"],
            ["idukki_kl", "伊都奇", "I"],
            ["incheon_kr", "仁川", "I"],
            ["indlovu_dc", "Indlovu DC", "I"],
            ["ingham_mi", "英厄姆县", "I"],
            ["innsbruck_inn", "因斯布鲁克", "I"],
            ["interlaken_int", "因特拉肯", "I"],
            ["ioannina", "约阿尼纳", "I"],
            ["ipoh_per", "怡保", "I"],
            ["irkutsk_g", "伊尔库茨克州", "I"],
            ["ishigaki", "石垣岛", "I"],
            ["islamabad_isl", "伊斯兰堡", "I"],
            ["island", "冰岛", "I"],
            ["isle_of_wight_eng", "怀特岛", "I"],
            ["istanbul_ist", "伊斯坦布尔", "I"],
            ["izmir_izm", "伊兹密尔", "I"],
            ["izu", "伊豆", "I"],
            ["izumisano_osa", "泉佐野市", "I"],
            ["jaen", "哈恩,安达卢西亚", "J"],
            ["jaipur_rj", "斋浦尔", "J"],
            ["jakarta", "雅加达", "J"],
            ["jasper_div", "贾斯珀", "J"],
            ["jeju", "济州岛", "J"],
            ["jerusalem_il", "耶路撒冷", "J"],
            ["jesolo_ve", "耶索洛", "J"],
            ["jinmen", "金门县", "J"],
            ["jodhpur_rj", "焦特布尔", "J"],
            ["johor_bahru_joh", "新山", "J"],
            ["kagoshima_kag", "鹿儿岛市", "K"]
            ,
            ["kainan", "海南市", "K"],
            ["kalibo_akl", "卡利博", "K"],
            ["kalutara_wp", "卡卢特勒", "K"],
            ["kamakura_kan", "镰仓市", "K"],
            ["kamikawa_district", "上川郡", "K"],
            ["kanazawa_ish", "金泽", "K"],
            ["kanchanaburi_th", "甘加那汶里府", "K"],
            ["kanchipuram_tn", "甘吉布勒姆", "K"],
            ["kandy", "康提", "K"],
            ["kaohsiung", "高雄市", "K"],
            ["karachi_kar", "卡拉奇", "K"],
            ["kathmandu_bag", "加德满都", "K"],
            ["kauhava_fi", "考哈瓦", "K"],
            ["kawasaki_kan", "川崎", "K"],
            ["keelung", "基隆市", "K"],
            ["kefalonia_prefecture", "凯法利尼亚 伊萨基州", "K"],
            ["kent_eng", "肯特", "K"],
            ["kent_mi", "肯特县", "K"],
            ["kentrikos_tomeas_athinon", "中雅典", "K"],
            ["kern_county", "克恩县", "K"],
            ["kerry_ker", "凯里郡", "K"],
            ["khabarovsk_g", "哈巴罗夫斯克", "K"],
            ["khanh_hoa_province", "庆和省", "K"],
            ["khon_kaen_th", "孔敬", "K"],
            ["kianggeh", "Kianggeh", "K"],
            ["kien_giang", "建江", "K"],
            ["kiev_kie", "基辅", "K"],
            ["king_county", "金县", "K"],
            ["kinondoni", "Kinondoni", "K"],
            ["kitakyushu_fuk", "北九州市", "K"],
            ["kitasaku_district", "北佐久郡", "K"],
            ["ko_lan_th", "阁兰岛", "K"],
            ["ko_lanta", "阁兰达岛", "K"],
            ["ko_li_pe", "丽贝岛", "K"],
            ["ko_pha_ngan", "帕岸岛", "K"],
            ["ko_phi_phi_don", "皮皮岛", "K"],
            ["ko_samet", "沙美岛", "K"],
            ["ko_sichang_th", "阁西昌岛", "K"],
            ["ko_tao_th", "涛岛", "K"],
            ["ko_yao_noi_th", "阁遥岛", "K"],
            ["kobe_hyo", "神户", "K"],
            ["kobenhavn", "哥本哈根", "K"],
            ["koh_chang_th", "象岛", "K"],
            ["koh_phuket_tha", "普吉", "K"],
            ["kolkata", "加尔各答", "K"],
            ["koror_kor", "科罗尔", "K"],
            ["kota_bharu_kel", "哥打巴鲁,吉兰丹", "K"],
            ["krabi_th", "甲米", "K"],
            ["krakow_kra", "克拉科夫", "K"],
            ["krong_preah_sihanouk", "西哈努克市", "K"],
            ["kuala_lumpur", "吉隆坡", "K"],
            ["kuala_terengganu_ter", "瓜拉登嘉楼", "K"],
            ["kuantan_pah", "关丹", "K"],
            ["kuching_sar", "古晋", "K"],
            ["kumamoto_kum", "熊本", "K"],
            ["kunigami_district", "国头郡", "K"],
            ["kusadasi", "库萨达斯", "K"],
            ["kuwait_city_al", "科威特城", "K"],
            ["kyoto_kyo", "京都", "K"],
            ["la_rioja_la", "拉里奥哈", "L"],
            ["laas_bz", "拉萨,博尔扎诺", "L"],
            ["lagos_ng", "拉各斯", "L"],
            ["lahore_lah", "拉合尔", "L"],
            ["lake", "莱克县,Indiana", "L"],
            ["lake_il", "Lake", "L"],
            ["lake_tekapo_can", "特卡波湖", "L"],
            ["lakonia_pel", "拉科尼亚", "L"],
            ["lam_dong", "Lam Dong", "L"],
            ["lancashire_eng", "兰开夏", "L"],
            ["lancaster_pa_us", "兰开斯特县", "L"],
            ["langkawi", "兰卡威", "L"],
            ["lao_cai_vn", "老街", "L"],
            ["laporte", "拉波特县", "L"],
            ["larnaca_cy", "拉纳卡区", "L"],
            ["las_palmas", "拉斯帕尔马斯", "L"],
            ["lasithi_cre", "拉西锡州", "L"],
            ["lausanne_lau", "洛桑", "L"],
            ["leicestershire_eng", "莱斯特郡", "L"],
            ["leipzig_lei", "莱比锡", "L"],
            ["leiria_district", "莱里亚", "L"],
            ["leon_cl", "利昂", "L"],
            ["lesbos_prefecture", "莱斯沃斯州", "L"],
            ["leukerbad_leu", "洛伊克巴德", "L"],
            ["lima_lim", "利马,利马", "L"],
            ["limassol", "利马索尔", "L"],
            ["lincolnshire_eng", "林肯郡", "L"],
            ["lisbon_pt", "里斯本", "L"],
            ["lleida_ct", "莱里达", "L"],
            ["london_england", "伦敦", "L"],
            ["long_xuyen", "龙川", "L"],
            ["los_angeles_ca", "洛杉矶", "L"],
            ["louangphabang", "琅勃拉邦", "L"],
            ["lucerne", "卢塞恩", "L"],
            ["lugo_ga", "卢戈,加利西亚", "L"],
            ["luxembourg", "卢森堡,卢森堡", "L"],
            ["luxor_lux", "卢克索", "L"],
            ["lyon_rho", "里昂", "L"],
            ["madison_al_us", "麦迪逊", "M"],
            ["madrid_com", "马德里自治区", "M"],
            ["mae_hong_son_th", "夜丰颂", "M"],
            ["magnisia", "Magnisia", "M"],
            ["malacca_mel", "马六甲", "M"],
            ["malaga_al", "马拉加", "M"],
            ["maldives", "马尔代夫", "M"],
            ["male_tn", "马莱", "M"],
            ["malta_spi", "马耳他", "M"],
            ["manama_cap", "麦纳麦", "M"],
            ["mandalay_man", "曼德勒", "M"],
            ["mandaue_city", "曼达维市", "M"],
            ["manila", "马尼拉", "M"],
            ["maricopa", "马里科帕,亚利桑那州", "M"],
            ["marin_county", "马林县", "M"],
            ["marion", "马里恩,Indiana", "M"],
            ["marrakesh", "马拉喀什", "M"],
            ["marseille_bou", "马赛", "M"],
            ["matale", "马特莱", "M"],
            ["maui_county", "茂宜郡", "M"],
            ["mauritius", "毛里求斯", "M"],
            ["mayo_may", "梅奥郡", "M"],
            ["mecca", "麦加", "M"],
            ["medan_nor", "棉兰", "M"],
            ["melbourne_australia", "墨尔本", "M"],
            ["mersyd", "默西赛德郡", "M"],
            ["messinia_pel", "Messinia", "M"],
            ["mexico_city_d_f", "墨西哥城", "M"],
            ["miami_dade", "迈阿密戴德县", "M"],
            ["miaoli_xian", "苗栗县", "M"],
            ["middlesex", "米德尔塞克斯县", "M"],
            ["middlesex_nj", "米德尔塞克斯", "M"],
            ["mikonos_not", "米科诺斯", "M"],
            ["milan_mi", "米兰", "M"],
            ["minamitsuru_district", "南都留郡", "M"],
            ["mirissa", "美蕊沙", "M"],
            ["miyako_district", "京都郡", "M"],
            ["miyakojima", "宫古岛市", "M"],
            ["mombasa_mom", "蒙巴萨", "M"],
            ["monaco_mc", "蒙特卡罗", "M"],
            ["monmouth", "蒙茅斯县", "M"],
            ["monroe_fl", "Monroe,Florida", "M"],
            ["monroe_ny", "Monroe,New York", "M"],
            ["monroe_pa", "Monroe,宾西法尼亚", "M"],
            ["monterey_county", "蒙特雷县", "M"],
            ["montgomery_pa", "蒙哥马利县,宾西法尼亚", "M"],
            ["montreal_mon", "蒙特利尔", "M"],
            ["montreux", "蒙特勒", "M"],
            ["morris_nj", "摩里斯县", "M"],
            ["moscow_g", "莫斯科", "M"],
            ["multnomah_county", "姆尔特诺默县", "M"],
            ["mumbai_suburban", "孟买", "M"],
            ["munich_m", "慕尼黑", "M"],
            ["murcia", "穆尔西亚", "M"],
            ["nagano_nag", "长野", "N"],
            ["nagasaki_nag", "长崎", "N"],
            ["nago_oki", "名护市", "N"],
            ["nagoya_aic", "名古屋", "N"],
            ["naha", "那霸", "N"],
            ["nainital_ut", "奈尼塔尔", "N"],
            ["nairobi_nai", "内罗毕,内罗毕", "N"],
            ["nakagami_district", "中头郡", "N"],
            ["nakhon_pathom_th", "佛统", "N"],
            ["nakhon_ratchasima_th", "呵叻府", "N"],
            ["nantou", "南投县", "N"],
            ["nanyo", "南阳市 山形", "N"],
            ["napa_county", "纳帕", "N"],
            ["naples", "那不勒斯,坎帕尼亚区", "N"],
            ["nara_nar", "奈良", "N"],
            ["narita_chi", "成田市", "N"],
            ["nassau_ny", "Nassau,New York", "N"],
            ["navarre_nav", "纳瓦拉", "N"],
            ["naxos", "纳克索斯", "N"],
            ["naypyidaw", "内比都", "N"],
            ["nesebar", "内塞伯尔", "N"],
            ["neshoba", "尼肖巴县", "N"],
            ["nevsehir", "内夫谢希尔", "N"],
            ["new_haven", "纽黑文县", "N"],
            ["new_providence", "New Providence", "N"],
            ["new_york_new", "纽约", "N"],
            ["niagara", "尼亚加拉县", "N"],
            ["niagara_falls_nia", "尼亚加拉瀑布城", "N"],
            ["nice_alp", "尼斯", "N"],
            ["nicosia", "尼科西亚区", "N"],
            ["nikko_toc", "日光市", "N"],
            ["nishimuro_district", "西牟娄郡", "N"],
            ["nisi", "Nisi", "N"],
            ["noboribetsu", "登别市", "N"],
            ["nonthaburi_th", "暖武里", "N"],
            ["norfolk", "罗福", "N"],
            ["norfolk_ma_us", "诺福克县", "N"],
            ["north_goa_ga", "果阿", "N"],
            ["north_lombok", "North Lombok", "N"],
            ["north_york", "北约克郡", "N"],
            ["northamptonshire_eng", "北安普敦郡", "N"],
            ["notios_tomeas_athinon", "Notios Tomeas Athinon", "N"],
            ["nottinghamshire_eng", "诺丁汉郡", "N"],
            ["novosibirsk_g", "新西伯利亚", "N"],
            ["nthumb", "诺森伯兰", "N"],
            ["nuremberg_mid", "纽伦堡", "N"],
            ["nuwara_eliya_cen", "努沃勒埃利耶", "N"],
            ["oah_honolulu", "檀香山,OAH", "O"],
            ["okayama_oka", "冈山", "O"],
            ["okinawa_city", "冲绳市", "O"],
            ["okinawa_oki", "冲绳", "O"],
            ["ommen_ov", "奥门", "O"],
            ["onondaga", "Onondaga", "O"],
            ["ontario", "安大略,New York", "O"],
            ["orange_county", "橙县", "O"],
            ["orange_fl", "奥朗日,佛罗里达", "O"],
            ["orange_ny", "奥兰治县", "O"],
            ["orkney_islands", "奥克尼群岛", "O"],
            ["orleans_la", "奥尔良,路易斯安娜州", "O"],
            ["osaka", "大阪", "O"],
            ["osceola_fl", "奥西欧拉县", "O"],
            ["oslo_osl", "奥斯陆", "O"],
            ["otaru_hok", "小樽市", "O"],
            ["ottawa_ott", "渥太华", "O"],
            ["overberg_dc", "Overberg DC", "O"],
            ["oxfordshire", "牛津郡", "O"],
            ["pa_philadelphia", "费城,PA", "P"],
            ["palau_ot", "帕劳", "P"],
            ["palencia", "帕伦西亚", "P"],
            ["palermo_pa", "巴勒莫", "P"],
            ["palm_beach_fl_us", "棕榈滩县", "P"],
            ["pamukkale", "棉花堡", "P"],
            ["panama", "巴拿马", "P"],
            ["pangkor_island_per", "邦咯岛", "P"],
            ["paphos", "帕福斯", "P"],
            ["paris_city", "巴黎", "P"],
            ["pattaya", "芭提雅", "P"],
            ["pembrokeshire", "彭布罗克郡", "P"],
            ["penango", "Penango", "P"],
            ["penghu_xian", "澎湖县", "P"],
            ["perth_and_kinross_sco", "珀斯 金罗斯", "P"],
            ["perth_wa", "珀斯", "P"],
            ["perugia_pg", "佩鲁贾", "P"],
            ["petaling_jaya_sel", "八打灵再也", "P"],
            ["phang_nga", "攀牙湾", "P"],
            ["phetchaburi", "佩布里", "P"],
            ["philadelphia_pa_us", "费城县", "P"],
            ["phnom_penh_new", "金边", "P"],
            ["phra_nakhon_si_ayutth_th", "大城府", "P"],
            ["pieria", "皮埃里亚州", "P"],
            ["pima", "Pima", "P"],
            ["pinellas", "皮尼拉斯县", "P"],
            ["pingdong_xian", "屏东县", "P"],
            ["pisa_pi", "比萨", "P"],
            ["pokhara_gan", "博克拉", "P"],
            ["pont_l_eveque_cal", "蓬莱韦克", "P"],
            ["pontevedra", "旁特维得拉", "P"],
            ["pora_pora", "博拉博拉岛", "P"],
            ["port_campbell", "坎贝尔港", "P"],
            ["port_dickson", "波德申", "P"],
            ["portalegre_district", "波塔莱格雷", "P"],
            ["porto_district", "波尔图", "P"],
            ["porto_velho", "波多韦柳", "P"],
            ["powys_wal", "波伊斯", "P"],
            ["prachuap_khiri_khan_th", "巴蜀府", "P"],
            ["prague_hla", "布拉格", "P"],
            ["pretoria_gp", "比勒陀利亚", "P"],
            ["province_of_ourense", "奥伦塞", "P"],
            ["puerto_galera_ori", "加莱拉港", "P"],
            ["puerto_princesa_pal", "公主港", "P"],
            ["pune_mh", "浦那", "P"],
            ["pyongyang_pyongyang", "平壤", "P"],
            ["quang_nam_province", "广南省", "Q"],
            ["quang_ninh_province", "广宁", "Q"],
            ["quebec_com", "魁北克", "Q"],
            ["queenstown_que", "皇后镇", "Q"],
            ["quito_canton", "基多", "Q"],
            ["r_r_district", "Ranga Reddy", "R"],
            ["ratchaburi_th", "拉差汶里", "R"],
            ["rayong", "罗永府", "R"],
            ["recoleta", "雷科莱塔", "R"],
            ["redang_island_ter", "热浪岛", "R"],
            ["rethymno", "雷西姆农州", "R"],
            ["reykjavik_cap", "雷克雅未克", "R"],
            ["rhodes_not", "罗德岛", "R"],
            ["ribeirao_preto", "里贝朗普雷图", "R"],
            ["richmond_gre", "列治文", "R"],
            ["riga_rig", "里加", "R"],
            ["ringkobing_skjern_municip", "灵克宾 斯凯恩自治市", "R"],
            ["rio_de_janeiro_rj", "里约热内卢", "R"],
            ["riverside_county", "里弗赛德县", "R"],
            ["riyadh_riy", "利雅得", "R"],
            ["rome_rm", "罗马", "R"],
            ["rothenburg_an", "罗滕堡", "R"]
            // ,
            // ["rotorua_rot", "罗托鲁瓦", "R"],
            // ["sabah", "沙巴", "S"],
            // ["sacramento_county", "萨克拉门托县", "S"],
            // ["saga_shi", "佐贺市", "S"],
            // ["saipan_mnp", "塞班岛", "S"],
            // ["salamanca_cl", "萨拉曼卡,卡斯蒂利亚 莱昂", "S"],
            // ["salt_lake_county", "盐湖县", "S"],
            // ["salzburg_sal", "萨尔茨堡", "S"],
            // ["samut_prakan", "沙没巴干", "S"],
            // ["samut_songkhram_th", "沙没颂堪", "S"],
            // ["san_bernardino_county", "San Bernardino County", "S"],
            // ["san_diego_county", "圣迭戈", "S"],
            // ["san_francisco_county", "旧金山", "S"],
            // ["san_jose_san", "圣何塞,圣荷西", "S"],
            // ["san_juan_san", "圣胡安", "S"],
            // ["san_luis_obispo_county", "圣路易斯 奥比斯波县", "S"],
            // ["san_mateo_county", "圣马刁县", "S"],
            // ["santa_barbara_county", "圣巴巴拉县", "S"],
            // ["santa_clara_county", "圣塔克拉拉县", "S"],
            // ["santa_cruz_de_tenerife_cn", "圣克鲁斯 德特内里费", "S"],
            // ["santarem_district", "考文垂", "S"],
            // ["santorini_not", "圣托里尼", "S"],
            // ["sao_paulo_sp", "圣保罗", "S"],
            // ["sapporo_hok", "札幌", "S"],
            // ["satun", "沙敦", "S"],
            // ["scottish_borders_sco", "苏格兰边境", "S"],
            // ["sedgwick", "Sedgwick", "S"],
            // ["segovia", "塞哥维亚省", "S"],
            // ["selcuk", "塞尔丘克", "S"],
            // ["sendai_miy", "仙台", "S"],
            // ["seoul", "首尔", "S"],
            // ["setubal_pt", "塞图巴尔区", "S"],
            // ["sevilla_al", "塞维利亚省", "S"],
            // ["seychelles_sey", "塞舌尔", "S"],
            // ["shah_alam", "莎阿南", "S"],
            // ["sharjah_sha", "沙迦", "S"],
            // ["sharm_el_sheikh_qes", "沙姆沙伊赫", "S"],
            // ["shizuoka_shi", "静冈", "S"],
            // ["shropshire_eng", "Shropshire", "S"],
            // ["siem_reap_cambodia", "暹粒市", "S"],
            // ["singapore_city", "新加坡", "S"],
            // ["siquijor_ph", "锡基霍尔", "S"],
            // ["sochi_gor", "索契", "S"],
            // ["sofia_sof", "索非亚", "S"],
            // ["somset", "萨默塞特", "S"],
            // ["sonderborg_municipality", "森讷堡自治市", "S"],
            // ["songkhla_th", "宋卡", "S"],
            // ["sonoma_county", "索诺马县", "S"],
            // ["soria", "索里亚", "S"],
            // ["south_cape_dc", "South Cape DC", "S"],
            // ["south_york", "南约克郡", "S"],
            // ["southampton_eng", "南安普顿", "S"],
            // ["st_charles_mo", "圣查尔斯县", "S"],
            // ["st_louis_mo", "圣路易斯,密苏里州", "S"],
            // ["st_petersburg_g", "圣彼得堡", "S"],
            // ["staffordshire_eng", "斯塔福德郡", "S"],
            // ["stockholm_sto", "斯德哥尔摩", "S"],
            // ["stone", "斯通县", "S"],
            // ["strasbourg_bas", "斯特拉斯堡", "S"],
            // ["stuttgart_s", "斯图加特", "S"],
            // ["suffolk", "苏佛克", "S"],
            // ["suffolk_ma", "沙福克县", "S"],
            // ["suffolk_ny", "苏福克郡", "S"],
            // ["sukhothai_th", "素可泰府", "S"],
            // ["sullivan_ny", "Sullivan", "S"],
            // ["sumy_sum", "苏梅", "S"],
            // ["surabaya_eas", "泗水", "S"],
            // ["surat_thani_th", "素叻他尼", "S"],
            // ["surrey", "萨里", "S"],
            // ["suwon_si", "水原市", "S"],
            // ["sydney_nsw", "悉尼", "S"],
            // ["tahiti", "大溪地", "T"],
            // ["taidong", "台东县", "T"],
            // ["tainan", "台南市", "T"],
            // ["taipei", "台北市", "T"],
            // ["taipei_xian", "新北市", "T"],
            // ["taizhong", "台中市", "T"],
            // ["takamatsu_kag", "高松", "T"],
            // ["takayama_gif", "高山市", "T"],
            // ["tallinn_tal", "塔林", "T"],
            // ["tangier_assilah", "Tangier Assilah", "T"],
            // ["taoyuan", "桃园县", "T"],
            // ["tarragona", "塔拉戈纳", "T"],
            // ["tarrant", "塔兰特县", "T"],
            // ["tashkent_uz", "塔什干", "T"],
            // ["taupo_tau", "陶波", "T"],
            // ["tay_ninh", "西宁,Tay Ninh", "T"],
            // ["tbilisi_did", "第比利斯", "T"],
            // ["tehran", "德黑兰", "T"],
            // ["tel_aviv_il", "特拉维夫", "T"],
            // ["teluk_intan_per", "安顺市", "T"],
            // ["teruel", "特鲁埃尔", "T"],
            // ["teton_wy", "提顿县", "T"],
            // ["the_hague_zh", "海牙", "T"],
            // ["thessaloniki_ken", "塞萨洛尼基", "T"],
            // ["thimphu_bt", "廷布", "T"],
            // ["tioman_island_my_mal", "刁曼岛", "T"],
            // ["tokoname_aic", "常滑市", "T"],
            // ["tokyo", "东京", "T"],
            // ["toledo", "托莱多,卡斯蒂利亚 拉曼查", "T"],
            // ["toronto_tor", "多伦多", "T"],
            // ["toulouse_hau", "图卢兹", "T"],
            // ["trang_th", "董里", "T"],
            // ["trat", "哒叻", "T"],
            // ["travis", "特拉维斯县", "T"],
            // ["trincomalee", "亭可马里", "T"],
            // ["turin_to", "都灵", "T"],
            // ["tyne_and_wear_eng", "泰恩 威尔郡", "T"],
            // ["udaipur_rj", "乌代布尔", "U"],
            // ["udon_thani_th", "乌隆他尼府", "U"],
            // ["ulaanbaatar", "乌兰巴托", "U"],
            // ["ulster", "阿尔斯特县", "U"],
            // ["urban", "Urban", "U"],
            // ["valencia_val", "巴伦西亚", "V"],
            // ["valladolid_cl", "瓦利阿多里德", "V"],
            // ["valletta", "瓦莱塔", "V"],
            // ["vancouver_gre", "温哥华", "V"],
            // ["varanasi_up", "瓦拉纳西", "V"],
            // ["varde_syd", "瓦德", "V"],
            // ["veere_ze", "费勒", "V"],
            // ["venice_ve", "威尼斯", "V"],
            // ["verona_vr", "维罗纳", "V"],
            // ["viana_do_castelo_district", "维亚纳堡", "V"],
            // ["victoria_cap", "维多利亚", "V"],
            // ["vienna_vie", "维也纳", "V"],
            // ["vientiane_capital", "万象市", "V"],
            // ["vila_real_district", "雷阿尔城", "V"],
            // ["vilnius_vil", "维尔纽斯", "V"],
            // ["viseu_district", "维塞乌", "V"],
            // ["vitacura", "Vitacura", "V"],
            // ["vladivostok_g", "符拉迪渥斯托克", "V"],
            // ["wakayama_wak", "和歌山", "W"],
            // ["wake", "韦克县", "W"],
            // ["warsaw_war", "华沙", "W"],
            // ["warwickshire", "沃里克郡", "W"],
            // ["wayne_mi_us", "韦恩", "W"],
            // ["wayne_pa_us", "韦恩,宾西法尼亚", "W"],
            // ["wellington_wel", "惠灵顿", "W"],
            // ["west_delhi", "West Delhi", "W"],
            // ["west_lombok", "West Lombok", "W"],
            // ["west_mids", "西米德兰兹郡", "W"],
            // ["west_susx", "西苏塞克斯", "W"],
            // ["west_york", "西约克郡", "W"],
            // ["westchester", "威斯特彻斯特郡", "W"],
            // ["western_district", "Western District", "W"],
            // ["whistler_squ", "惠斯勒", "W"],
            // ["wiltshire_eng", "威尔特郡", "W"],
            // ["windham_vt_us", "温德姆县", "W"],
            // ["windsor_vt_us", "温莎县", "W"],
            // ["windward_islands", "向风群岛", "W"],
            // ["winnipeg_div", "温尼伯", "W"],
            // ["worcester_ma_us", "伍斯特,马萨诸塞州", "W"],
            // ["worcestershire_eng", "伍斯特郡", "W"],
            // ["wyoming_pa", "Wyoming", "W"],
            // ["xinzhu", "新竹县", "X"],
            // ["xinzhuxian", "新竹市", "X"],
            // ["yamanashi_yam", "山梨市", "Y"],
            // ["yangon_yan", "仰光", "Y"],
            // ["yekaterinburg_yek", "叶卡捷琳堡", "Y"],
            // ["yeosu_si", "丽水市", "Y"],
            // ["yilan_taiwan", "宜兰县", "Y"],
            // ["yogyakarta_city", "日惹", "Y"],
            // ["yokohama_kan", "横滨", "Y"],
            // ["york_eng", "约克", "Y"],
            // ["yunlin", "云林县", "Y"],
            // ["zagreb_cit", "萨格勒布", "Z"],
            // ["zakinthos_ion", "扎金索斯", "Z"],
            // ["zamora_cl", "萨莫拉", "Z"],
            // ["zaragoza_ara", "萨拉戈萨省", "Z"],
            // ["zurich_zur", "苏黎世", "Z"]
        ]
    }
};